GH-518 CI: Use ubuntu-latest instead of macos runner with BSDs.
It seems macos runners are being phased out and no longer working. VM setup
phase logs a warning and then fails:

   Warning: Support for macOS runners has been deprecated and will be removed
   ina future update. Please use the `ubuntu-latest` runner instead.
   ...
   Initializing VM
   Error: The process '/usr/bin/sudo' failed with exit code null

Switching to ubuntu-latest runner fixes the above and allows the tests to pass.