GH-438 Remove 'extern "C"' wrapper around Perl XS includes.
'extern "C" {}' block has wrapped Perl XS standard includes since the
beginning.  The earliest version found from the net is Net_SSLeay.pm version
0.4 in which the following was already present:

  #ifdef __cplusplus
  extern "C" {
  #endif
  #include "EXTERN.h"
  #include "perl.h"
  #include "XSUB.h"
  #ifdef __cplusplus
  }
  #endif

This has been carried over since then, until the recent SSLeay.xs updates to
allow compilation with a C++ compiler caused a compilation failure.

Recent GCC and Clang C++ compilers do not care about the 'extern "C"' wrapper
but Visual Studio Community 2022 flagged the following error (see GH-438):

C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\wspiapi.h(53):
error C2894: templates cannot be declared to have 'C ' linkage

When 'extern "C" {}' is removed completely, the compilation succeeds. This
makes sense since apparently the purpose of 'extern "C" {}' is to wrap one's
own functions instead of headers included from elsewhere. Those headers should
have their own 'extern "C" {}' definitions, if any are needed.